import type { Repository } from './types';

function generateMarkdown(repos: Repository[]): string {
    const date = new Date().toLocaleDateString();
    let content = `# My Repository Collection\n\nGenerated by Repo Ranger on ${date}\n\n## Repositories (${repos.length})\n\n`;

    repos.forEach(repo => {
        content += `- **[${repo.full_name}](${repo.html_url})** - ⭐ ${repo.stargazers_count.toLocaleString()} - ${repo.description || 'No description'}\n`;
    });

    return content;
}

function generateJSON(repos: Repository[]): string {
    const data = {
        exported_by: "Repo Ranger",
        export_date: new Date().toISOString(),
        repository_count: repos.length,
        repositories: repos.map(repo => ({
            owner: repo.owner.login,
            repo: repo.name,
            full_name: repo.full_name,
            description: repo.description,
            stars: repo.stargazers_count,
            forks: repo.forks_count,
            language: repo.language,
            license: repo.license?.name || null,
            url: repo.html_url,
            topics: repo.topics || []
        }))
    };
    return JSON.stringify(data, null, 2);
}

function generateCSV(repos: Repository[]): string {
    const header = "Name,Owner,Stars,Forks,Language,License,URL,Description\n";
    
    const rows = repos.map(repo => {
        const name = repo.name;
        const owner = repo.owner.login;
        const stars = repo.stargazers_count;
        const forks = repo.forks_count;
        const language = repo.language || '';
        const license = repo.license?.name || '';
        const url = repo.html_url;
        // Descriptions can have commas, so we need to wrap them in quotes.
        const description = `"${(repo.description || '').replace(/"/g, '""')}"`;
        return [name, owner, stars, forks, language, license, url, description].join(',');
    });

    return header + rows.join('\n');
}

function generateText(repos: Repository[]): string {
    const date = new Date().toUTCString();
    let content = `Repo Ranger - Repository List\nExported: ${date}\n\n`;
    content += repos.map(repo => repo.html_url).join('\n');
    return content;
}

export function generateExportContent(format: 'md' | 'json' | 'csv' | 'txt', repos: Repository[]): string {
    switch (format) {
        case 'md': return generateMarkdown(repos);
        case 'json': return generateJSON(repos);
        case 'csv': return generateCSV(repos);
        case 'txt': return generateText(repos);
        default: return '';
    }
}

export function triggerDownload(content: string, filename: string, mimeType: string) {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}
