'use server';

import { getSummarizedInstallationGuide } from '@/lib/ai';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Wand2 } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeRaw from 'rehype-raw';

export async function InstallationGuide({ owner, repo, readmeContent }: { owner: string, repo: string, readmeContent: string }) {
  if (!readmeContent || readmeContent.trim() === 'No README found.') {
    return null;
  }

  try {
    const { summary } = await getSummarizedInstallationGuide({ readmeContent }, owner, repo);
      
    // Don't render the component if AI is not configured or fails to produce a summary.
    if (!summary || summary.includes('AI features are not configured')) {
      return null;
    }
    
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Wand2 className="text-primary" />
            AI-Powered Installation Guide
          </CardTitle>
          <CardDescription>A summary of installation steps, generated by AI.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="prose dark:prose-invert max-w-none prose-sm sm:prose-base prose-pre:bg-secondary/50 prose-pre:rounded-md">
            <ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeRaw]}>
                {summary}
            </ReactMarkdown>
          </div>
        </CardContent>
      </Card>
    );
  } catch (error) {
    console.error("Failed to generate AI installation guide:", error);
    // Fail gracefully without crashing the page if the AI feature has an issue.
    return null;
  }
}
